% Code to call MATLAB functions generated by Classification Learner App
% to train selected machine learning algorithms with training data.
% Newly trained classifiers are then saved to a model which can be used in
% simulation or converted to embedded code using MATLAB Coder.
%
% Copyright 2017-2018 The MathWorks, Inc.

% If necessary, load previously generated training data
if(~exist('algo_training_data','var'))
    disp('Variable algo_training_data not in workspace.');
    disp('Attempting to load previously generated results...');
    try
        load('sm_pump_triplex_fault_detect_algo_training_data.mat');
        disp('... loaded sm_pump_triplex_fault_detect_algo_training_data.mat ');
    catch
        error('Could not load sm_pump_triplex_fault_detect_algo_training_data.mat');
    end
end

% If necessary, disable warnings to avoid cluttering Live Script
warning('off','stats:classreg:learning:modifier:AdaBoostM2:modify:NonPositiveLoss')

% Train learners and save results to workspace
[boostedTreeClass, ~]   = sm_pump_triplex_train_boostedTreeClass(algo_training_data);
[boostedTreeNumeric, ~] = sm_pump_triplex_train_boostedTreeNumeric(algo_training_data);

% If necessary, re-enable warnings
warning('on','stats:classreg:learning:modifier:AdaBoostM2:modify:NonPositiveLoss')

% Save trained classifiers to a .mat file
% Date and time can be appended to avoid overwriting an existing file
avoidOverwrite = 0;  % Set to 0 during doc publish (permit overwrite)
if(avoidOverwrite)
    filenameSuffix = ['_' datestr(now,'yymmdd_HHMM')];
else
    filenameSuffix = '';
end

save(['sm_pump_triplex_trained_classifiers' filenameSuffix '.mat'],...
    'boostedTreeClass','boostedTreeNumeric');

% Create model for use in simulation or for conversion to embedded code
compactMdl = boostedTreeNumeric.ClassificationEnsemble;
saveCompactModel(compactMdl,['sm_pump_triplex_fault_detect_algo' filenameSuffix]);
